name 'aar'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures aar'
long_description 'Installs/Configures aar'
version '0.1.0'

depends 'apt'
depends 'python', '~> 1.4.6'
depends 'mysql2_chef_gem'
depends 'database', '~> 5.1.2'
